{
 "title": "NGSA - Fluent Bit",
 "description": "Inspired by https://grafana.com/grafana/dashboards/7752 and https://docs.fluentbit.io/manual/administration/monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Input Bytes Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total[5m])) by (instance, name)",
     "legendFormat": "{{ instance }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Bytes Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total[5m])) by (instance, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Input Records Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[5m])) by (instance, name)",
     "legendFormat": "{{ instance }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Record Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total[5m])) by (instance, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Retry/Failed Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total[1m])) by (instance, name)",
     "legendFormat": "{{instance}} Retries to {{name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total[1m])) by (instance, name)",
     "legendFormat": "{{instance}} Failed Retries to {{ name }}"
    }
   ]
  },
  {
   "title": "Output Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "errors/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total[1m])) by (instance, name)",
     "legendFormat": "{{ instance }}/{{ name }}"
    }
   ]
  },
  {
   "title": "FluentBit Pods Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "expr": "up{job=\"fluentbit\"} == 1",
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  }
 ]
}