---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loki-repo
  namespace: logging
spec:
  interval: 1m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-release
  namespace: logging
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: loki
      version: 4.3.0
  interval: 1m0s
