---
apiVersion: v1
kind: Namespace
metadata:
  name: loki

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-values
  labels:
    name: loki-values
  namespace: loki
data:
  loki-values.yaml: |-
    loki:
      storage:
        type: azure
        azure:
          accountName: k6labssa
          userAssignedId: /subscriptions/dfc66ce2-45ce-43c5-a084-906790c73ed2/resourcegroups/rg-k6labs-storage/providers/Microsoft.ManagedIdentity/userAssignedIdentities/lokiasidentity
     