apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-values
  labels:
    name: loki-values
  namespace: logging
data:
  loki-values.yaml: |-
    loki:
      config: |
        auth_enabled: false

        server:
          http_listen_port: 3100

        common:
          path_prefix: /var/loki
          
          storage:
            azure:
              use_managed_identity: true
              account_name: k6labssa
              container_name: loki
              user_assigned_id: /subscriptions/dfc66ce2-45ce-43c5-a084-906790c73ed2/resourcegroups/rg-k6labs-storage/providers/Microsoft.ManagedIdentity/userAssignedIdentities/lokiasidentity

          ring:
            kvstore:
              store: memberlist

        compactor:
          working_directory: /var/loki/retention
          shared_store: azure
          retention_enabled: true

        limits_config:
          retention_period: 168h

        memberlist:
          join_members:
            - {{ include "loki.name" . }}-memberlist

        schema_config:
          configs:
          - from: "2020-12-11"
            index:
              period: 24h
              prefix: index_
            object_store: azure
            schema: v11
            store: boltdb-shipper

        storage_config:
          boltdb_shipper:
            active_index_directory: /var/loki/boltdb-shipper-active
            cache_location: /var/loki/boltdb-shipper-cache
            cache_ttl: 24h
            shared_store: azure

          filesystem:
            directory: /var/loki/chunks
