---
apiVersion: v1
kind: Namespace
metadata:
  name: loki

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://grafana.github.io/helm-charts
  
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1m0s
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 4.3.0
  values:
      service:
        grpcService: backend
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
      loki:
        auth_enabled: false
        storage:
          type: azure
          azure:
            accountName: k6labssa
            userAssignedId: f724bc60-bc7d-4d49-a802-29283b99249d
