---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: visualization 
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:9.1.0
          imagePullPolicy: IfNotPresent    
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - name: dashboards-ngsa
              mountPath: /var/lib/grafana/dashboards/ngsa
            - name: dashboards-dotnet
              mountPath: /var/lib/grafana/dashboards/dotnet
            - name: dashboards-ngsa-fluentbit
              mountPath: /var/lib/grafana/dashboards/ngsa-fluentbit     
            - name: dashboards-prometheus
              mountPath: /var/lib/grafana/dashboards/prometheus          
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: false
            - name: grafana-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboardProvider.yaml
              subPath: dashboardProvider.yaml             
      volumes:
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: dashboards-ngsa
          configMap:
            name: grafana-dashboards-ngsa
        - name: dashboards-dotnet
          configMap:
            name: grafana-dashboards-dotnet
        - name: dashboards-ngsa-fluentbit
          configMap:
            name: grafana-dashboards-ngsa-fluentbit
        - name: dashboards-prometheus
          configMap:
            name: grafana-dashboards-prometheus
        - name: grafana-secrets
          secret:
            secretName: grafana-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: visualization 
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
