---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
  namespace: visualization
spec:
  interval: 1m0s # detect drift and undo kubectl edits every minute
  prune: true # remove stale resources from cluster
  path: ./deploy/monitoring/grafana/grafana
  sourceRef:
    kind: GitRepository
    name: aks-repo-flux
    namespace: flux-system # points to namespace where this GitRepository is
