
---
apiVersion: v1
kind: Namespace
metadata:
  name: promtail
  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: promtail
  namespace: promtail
spec:
  interval: 1m0s # detect drift and undo kubectl edits every minute
  prune: true # remove stale resources from cluster
  path: ./deploy/monitoring/grafana/promtail
  sourceRef:
    kind: GitRepository
    name: aks-repo-flux
    namespace: flux-system # points to namespace where this GitRepository is
